### ISSUE TITLE
Power off detection

### ISSUE THREAD

**Issue by marcgarciamarti** [hchris1/Eversolo#53]
### Is your feature request related to a problem? Please describe.

I would like to detect when the Eversolo is powered up and when it is powered down. I have a few automations in place that will monitor when Eversolo comes either on or off, and they take care of powering up or down my power amplifier and my DAC, etc.
However, they don't work 100% reliably and I believe it is because of the way HA treats the media_player entity. 

This is how my power on automation is coded:
```
alias: Eversolo powers on
description: >-
  This automation will make sure volume is acceptably low before powering on the
  amplifier
trigger:
  - platform: state
    entity_id:
      - media_player.eversolo
    from: unavailable
    to: null
  - platform: state
    entity_id:
      - media_player.eversolo
    from: unknown
    to: null
condition:
  - condition: template
    value_template: "{{ is_state('media_player.eversolo', ['on', 'playing', 'idle']) }}"
    enabled: true
```

and this is how the power off automation is coded:
```
alias: Eversolo powers off
description: >-
  This automation will switch off the CXA61 amplifier and then power off the
  wall socket
trigger:
  - platform: device
    device_id: 86887090ddc551a36bc3a50009726146
    domain: button
    entity_id: fa94f524abc0a8944ab2f0fc304a11ef
    type: pressed
```

### Describe the solution you'd like

It would be awesome if I this integration managed to flag to HA when the Eversolo just powered up or when it powered down

### Describe alternatives you've considered

I'm considering implementing a state machine wrapped around the mediaplayer integration in order to build my own sequence, but I'm not sure if that is the best approach

### Additional context

none

**Comment by hchris1** [comment]
Hi @marcgarciamarti,

I have similiar automations working quite reliably for me. Maybe the condition in your power on automation is causing this issue? Here are the triggers I use:

---

```yaml
alias: Eversolo available
description: ""
trigger:
  - platform: state
    entity_id:
      - media_player.eversolo
    from: unavailable
    to: null
condition: []
action:
  - service: persistent_notification.create
    metadata: {}
    data:
      message: Eversolo turned on!
mode: single
```

```yaml
alias: Eversolo unavailable
description: ""
trigger:
  - platform: state
    entity_id:
      - media_player.eversolo
    from: null
    to: unavailable
condition: []
action:
  - service: persistent_notification.create
    metadata: {}
    data:
      message: Eversolo turned off!
mode: single
```

---
From an integration perspective, there's not a lot I can provide here. An additional signal for a power up would be available at the same time the media player (or any other Eversolo entity) becomes available. 

A different approach to your problem would be the usage of a PING entity ([Link to HA docs](https://www.home-assistant.io/integrations/ping/)). This will provide you a binary sensor that you can further use in your automations.

Chris
